version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_DATABASE: spikeguard
      MYSQL_USER: spikeuser
      MYSQL_PASSWORD: 111
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth
    container_name: auth_service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://spikeuser:111@mysql/spikeguard
    depends_on:
      mysql:
        condition: service_healthy
